# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: A list of interesting links, curated by Daniel Fosco
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://danielfos.co" # the base hostname & protocol for your site
twitter_username: notdanielfosco
github_username:  dfosco

# Build settings
markdown: kramdown

gems: [bourbon, bitters, neat]