# Site settings
title: Case Study
email: danielfosco@gmail.com
description: "Portfolio website for Product Designer Daniel Fosco."
baseurl: /portfolio
url: http://dfosco.gihub.io/portfolio
twitter_username: notdanielfosco
github_username:  dfosco
gems: [jekyll-sass]

# Build settings
markdown: kramdown
permalink: pretty

# defaults
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: true   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory