# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: "The Link List"
baseurl: "http://dfosco.github.io"

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
markdown: kramdown

sass:
    style: :compressed


collections:
  links:
    output: true