# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: "Hi. I'm Daniel Fosco, a freelance designer & developer. I make things for web + mobile."
baseurl: "http://dfosco.github.io"
url: "http://danielfos.co"

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
connection: online
sass:
    style: :compressed

permalink: "/notes/:title"
paginate: 25
paginate_path: "/notes/page:num/"

# Collection settings
collections:
  items:
    output: true
  buckets:
    output: true
    permalink: /buckets/:path/
  works:
    output: true
    permalink: /work/:path/
  docs:
    output: true
    permalink: /docs/:path/    
