# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: "The Link List"
baseurl: "http://dfosco.github.io"
permalink: /:categories/:title

gems: [jekyll-paginate]

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
markdown: kramdown
connection: online

sass:
    style: :compressed

paginate: 10
paginate_path: "/links/page:num/"