# Site settings
title: Daniel Fosco -- Product Designer
email: danielfosco@gmail.com
description: "Website of Product Designer Daniel Fosco."
baseurl: 
url: http://danielfos.co
gems: [jekyll-sass]

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
markdown: kramdown
permalink: pretty

# defaults
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: true   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory