# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: "Hi, my name is Daniel and this is my website. Hope you enjoy it."
baseurl: "http://dfosco.github.io"
domain: "http://danielfos.co"

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
connection: online
sass:
    style: :compressed

permalink: "/:categories/:title"
paginate: 10
paginate_path: "/links/page:num/"

# Collection settings
collections:
  items:
    output: true
  buckets:
    output: true
    permalink: /collections/:path/
