# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: "Portfolio of Daniel Fosco"
baseurl: http://dfosco.github.io

exclude: [/links/source]

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title